version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: dailytrends-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: dailytrends
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
